// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IDeployer$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IDeployer";
  readonly sourceName: "contracts/interfaces/IDeployer.sol";
  readonly abi: [{"inputs":[{"internalType":"bytes","name":"code","type":"bytes"},{"internalType":"uint256","name":"salt","type":"uint256"}],"name":"deploy","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"bytes","name":"code","type":"bytes"},{"internalType":"uint256","name":"salt","type":"uint256"},{"internalType":"address","name":"expectedAddress","type":"address"}],"name":"deployAt","outputs":[],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/interfaces/IDeployer.sol";
  readonly buildInfoId: "solc-0_8_28-3dff9d61f6fe1de5023486fe0c458e4e34683028";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IDeployer"]: IDeployer$Type;
    ["contracts/interfaces/IDeployer.sol:IDeployer"]: IDeployer$Type;
  }
}