// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface RegistryAware$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "RegistryAware";
  readonly sourceName: "contracts/RegistryAware.sol";
  readonly abi: [{"inputs":[{"internalType":"address","name":"_registry","type":"address"}],"stateMutability":"nonpayable","type":"constructor"},{"inputs":[],"name":"OnlyMember","type":"error"},{"inputs":[{"internalType":"uint256","name":"currentState","type":"uint256"},{"internalType":"uint256","name":"checks","type":"uint256"}],"name":"Paused","type":"error"},{"inputs":[{"internalType":"address","name":"caller","type":"address"},{"internalType":"uint256","name":"callerIndex","type":"uint256"},{"internalType":"uint256","name":"authorizedBitmap","type":"uint256"}],"name":"Unauthorized","type":"error"},{"inputs":[],"name":"registry","outputs":[{"internalType":"contract IRWIRegistry","name":"","type":"address"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x60a0604052348015600e575f5ffd5b5060405161011d38038061011d833981016040819052602b91603b565b6001600160a01b03166080526066565b5f60208284031215604a575f5ffd5b81516001600160a01b0381168114605f575f5ffd5b9392505050565b60805160a261007b5f395f602e015260a25ff3fe6080604052348015600e575f5ffd5b50600436106026575f3560e01c80637b10399914602a575b5f5ffd5b60507f000000000000000000000000000000000000000000000000000000000000000081565b6040516001600160a01b03909116815260200160405180910390f3fea2646970667358221220665f02e147bc4df22ab795207f5097b4eacf86658c4c01ac17a69464050c41b464736f6c634300081c0033";
  readonly deployedBytecode: "0x6080604052348015600e575f5ffd5b50600436106026575f3560e01c80637b10399914602a575b5f5ffd5b60507f000000000000000000000000000000000000000000000000000000000000000081565b6040516001600160a01b03909116815260200160405180910390f3fea2646970667358221220665f02e147bc4df22ab795207f5097b4eacf86658c4c01ac17a69464050c41b464736f6c634300081c0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {"3904":[{"length":32,"start":46}]};
  readonly inputSourceName: "project/contracts/RegistryAware.sol";
  readonly buildInfoId: "solc-0_8_28-a2c91f5c1d7a633cf04581d80caba64768c511b2";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["RegistryAware"]: RegistryAware$Type;
    ["contracts/RegistryAware.sol:RegistryAware"]: RegistryAware$Type;
  }
}